export const studentPersona = [
  {
    id: 1,
    first_name: "Evelyn",
    last_name: "Thorneloe",
    Age: 30,
    email: "rthorneloe0@imgur.com",
    Photo: "https://randomuser.me/api/portraits/women/67.jpg",
  },
  {
    id: 2,
    first_name: "Aranka",
    last_name: "Dearnaly",
    Age: 38,
    email: "ddearnaly1@symantec.com",
    Photo: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    id: 3,
    first_name: "Floris",
    last_name: "Maclean",
    Age: 21,
    email: "smaclean2@themeforest.net",
    Photo: "https://randomuser.me/api/portraits/men/85.jpg",
  },
  {
    id: 4,
    first_name: "Hector",
    last_name: "Honniebal",
    Age: 31,
    email: "nhonniebal3@instagram.com",
    Photo: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    id: 5,
    first_name: "Martina",
    last_name: "Sancraft",
    Age: 20,
    email: "hsancraft4@google.fr",
    Photo: "https://randomuser.me/api/portraits/women/58.jpg",
  },
  {
    id: 6,
    first_name: "Maurits",
    last_name: "Abelwhite",
    Age: 29,
    email: "dabelwhite5@delicious.com",
    Photo: "https://randomuser.me/api/portraits/men/68.jpg",
  },
  {
    id: 7,
    first_name: "Rahima",
    last_name: "Overthrow",
    Age: 23,
    email: "roverthrow6@techcrunch.com",
    Photo: "https://randomuser.me/api/portraits/women/61.jpg",
  },
  {
    id: 8,
    first_name: "Sandra",
    last_name: "Tassell",
    Age: 27,
    email: "ntassell7@joomla.org",
    Photo: "https://randomuser.me/api/portraits/women/53.jpg",
  },
  {
    id: 9,
    first_name: "Wietske",
    last_name: "Panswick",
    Age: 34,
    email: "cpanswick8@loc.gov",
    Photo: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 10,
    first_name: "Storm",
    last_name: "Toye",
    Age: 27,
    email: "stoye9@hugedomains.com",
    Photo: "https://randomuser.me/api/portraits/men/79.jpg",
  },
];
